/* Generated By:JJTree: Do not edit this line. ASTArray.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

public
class ASTArray extends SimpleNode {
  public ASTArray(int id) {
    super(id);
  }

  public ASTArray(Yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6f0fce28245b5dde64afe9d0e1f10356 (do not edit this line) */
