/* Generated By:JJTree: Do not edit this line. ASTArrayAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

import custom.ASTWithName;

public
class ASTArrayAccess extends SimpleNode{
  
	String name;
	public ASTArrayAccess(int id) {
    super(id);
  }
  
  public ASTArrayAccess(Yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0f50e57e2131adaf5f701d1c07fea373 (do not edit this line) */
