/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

public
class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(Yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d4632d6eb5e4284a8ff69621c487ef7c (do not edit this line) */
