/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

public
class ASTModule extends SimpleNode {
  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(Yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=100ef1b6e39cf9e27d8b68e14528c8ee (do not edit this line) */
