/* Generated By:JJTree: Do not edit this line. ASTParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

public
class ASTParameters extends SimpleNode {
  public ASTParameters(int id) {
    super(id);
  }

  public ASTParameters(Yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dffe6b00c960f234b68927c0713daf03 (do not edit this line) */
