/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

public
class ASTReturn extends SimpleNode {
  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(Yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f5d606ab0ae79934ae46f9f64dac90f (do not edit this line) */
