/* Generated By:JJTree: Do not edit this line. ASTStatements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

public
class ASTStatements extends SimpleNode {
  public ASTStatements(int id) {
    super(id);
  }

  public ASTStatements(Yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=037b6ed495a14113420055f2de0f95da (do not edit this line) */
