/* Generated By:JJTree: Do not edit this line. ASTScalarVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

import custom.ASTWithName;

public
class ASTScalarVariable extends SimpleNode implements ASTWithName {
	String name;
  public ASTScalarVariable(int id) {
    super(id);
  }

  public ASTScalarVariable(Yal2jvm p, int id) {
    super(p, id);
  }

@Override
public String getName() {
	return name;
}

}
/* JavaCC - OriginalChecksum=90c3751895bf33c15604ca23ac3e8605 (do not edit this line) */
