/* Generated By:JJTree: Do not edit this line. ASTSizeof.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

public
class ASTSizeof extends SimpleNode {
  public ASTSizeof(int id) {
    super(id);
  }

  public ASTSizeof(Yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ee49a97aa745a565517a1b478bc73e54 (do not edit this line) */
