/* Generated By:JJTree: Do not edit this line. ASTVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm;

public
class ASTVariable extends SimpleNode {
	String name;
	
  public ASTVariable(int id) {
    super(id);
  }

  public ASTVariable(Yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a1d0fc6aa8ec7eae3d53ea77f0de2b9 (do not edit this line) */
