/* Generated By:JavaCC: Do not edit this line. Yal2jvmTreeConstants.java Version 5.0 */
package yal2jvm;

public interface Yal2jvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTVOID = 1;
  public int JJTARRAY = 2;
  public int JJTDECLARE = 3;
  public int JJTINTEGER = 4;
  public int JJTFUNCTION = 5;
  public int JJTARRAYVARIABLE = 6;
  public int JJTSCALARVARIABLE = 7;
  public int JJTRETURN = 8;
  public int JJTPARAMETERS = 9;
  public int JJTSTATEMENTS = 10;
  public int JJTARRAYACCESS = 11;
  public int JJTVARIABLE = 12;
  public int JJTASSIGN = 13;
  public int JJTMODULEACCESS = 14;
  public int JJTCALL = 15;
  public int JJTOPERATOR = 16;
  public int JJTNEGATION = 17;
  public int JJTSIZEOF = 18;
  public int JJTCONDITION = 19;
  public int JJTWHILE = 20;
  public int JJTIF = 21;
  public int JJTARGUMENTLIST = 22;
  public int JJTSTRING = 23;
  public int JJTINDEX = 24;


  public String[] jjtNodeName = {
    "Module",
    "void",
    "Array",
    "Declare",
    "Integer",
    "Function",
    "ArrayVariable",
    "ScalarVariable",
    "Return",
    "Parameters",
    "Statements",
    "ArrayAccess",
    "Variable",
    "Assign",
    "ModuleAccess",
    "Call",
    "Operator",
    "Negation",
    "Sizeof",
    "Condition",
    "While",
    "If",
    "ArgumentList",
    "String",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=77b31eacc31ff3f03e64f5f4eb5126f0 (do not edit this line) */
