/* Generated By:JavaCC: Do not edit this line. Yal2jvmTreeConstants.java Version 5.0 */
package yal2jvm;

public interface Yal2jvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTVOID = 1;
  public int JJTARRAY = 2;
  public int JJTDECLARE = 3;
  public int JJTINTEGER = 4;
  public int JJTFUNCTION = 5;
  public int JJTARRAYVARIABLE = 6;
  public int JJTSCALARVARIABLE = 7;
  public int JJTRETURN = 8;
  public int JJTPARAMETERS = 9;
  public int JJTSTATEMENTS = 10;
  public int JJTARRAYACCESS = 11;
  public int JJTVARIABLE = 12;
  public int JJTASSIGN = 13;
  public int JJTCALL = 14;
  public int JJTOPERATOR = 15;
  public int JJTNEGATION = 16;
  public int JJTSIZEOF = 17;
  public int JJTCONDITION = 18;
  public int JJTWHILE = 19;
  public int JJTIF = 20;
  public int JJTARGUMENTLIST = 21;
  public int JJTSTRING = 22;
  public int JJTINDEX = 23;
  public int JJTERROR_SKIPTO = 24;


  public String[] jjtNodeName = {
    "Module",
    "void",
    "Array",
    "Declare",
    "Integer",
    "Function",
    "ArrayVariable",
    "ScalarVariable",
    "Return",
    "Parameters",
    "Statements",
    "ArrayAccess",
    "Variable",
    "Assign",
    "Call",
    "Operator",
    "Negation",
    "Sizeof",
    "Condition",
    "While",
    "If",
    "ArgumentList",
    "String",
    "Index",
    "error_skipto",
  };
}
/* JavaCC - OriginalChecksum=20b297eb92fd1949f585506a9a0a121b (do not edit this line) */
