/* Generated By:JavaCC: Do not edit this line. Yal2jvmTreeConstants.java Version 5.0 */
public interface Yal2jvmTreeConstants
{
  public int JJTSTART = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTVARLIST = 3;
  public int JJTELEMENT = 4;
  public int JJTSTMTLST = 5;
  public int JJTSTMT = 6;
  public int JJTSTMTCALLORASSIGN = 7;
  public int JJTASSIGN = 8;
  public int JJTRHS = 9;
  public int JJTARRAYSIZE = 10;
  public int JJTTERM = 11;
  public int JJTCALLORACCESS = 12;
  public int JJTEXPRTEST = 13;
  public int JJTWHILE = 14;
  public int JJTIF = 15;
  public int JJTCALL = 16;
  public int JJTARGUMENTLIST = 17;
  public int JJTARGUMENT = 18;
  public int JJTACCESS = 19;
  public int JJTSCALARACCESS = 20;
  public int JJTINDEX = 21;


  public String[] jjtNodeName = {
    "Start",
    "Declaration",
    "Function",
    "Varlist",
    "Element",
    "Stmtlst",
    "Stmt",
    "StmtCallOrAssign",
    "Assign",
    "Rhs",
    "ArraySize",
    "Term",
    "CallOrAccess",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "Access",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=228ae5405424ff3f0292ab59fbc76a28 (do not edit this line) */
