/* Generated By:JavaCC: Do not edit this line. Yal2jvmTreeConstants.java Version 5.0 */
public interface Yal2jvmTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEX_DECLARATION = 1;
  public int JJTDECLARATION = 2;
  public int JJTFUNCTION = 3;
  public int JJTVARLIST = 4;
  public int JJTELEMENT = 5;
  public int JJTSTMTLST = 6;
  public int JJTSTMT = 7;
  public int JJTSTMTCALLORASSIGN = 8;
  public int JJTASSIGN = 9;
  public int JJTRHS = 10;
  public int JJTARRAYSIZE = 11;
  public int JJTTERM = 12;
  public int JJTCALLORACCESS = 13;
  public int JJTEXPRTEST = 14;
  public int JJTWHILE = 15;
  public int JJTIF = 16;
  public int JJTCALL = 17;
  public int JJTARGUMENTLIST = 18;
  public int JJTARGUMENT = 19;
  public int JJTACCESS = 20;
  public int JJTSCALARACCESS = 21;
  public int JJTINDEX = 22;
  public int JJTERROR_SKIPTO = 23;


  public String[] jjtNodeName = {
    "Start",
    "Ex_Declaration",
    "Declaration",
    "Function",
    "Varlist",
    "Element",
    "Stmtlst",
    "Stmt",
    "StmtCallOrAssign",
    "Assign",
    "Rhs",
    "ArraySize",
    "Term",
    "CallOrAccess",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "Access",
    "ScalarAccess",
    "Index",
    "error_skipto",
  };
}
/* JavaCC - OriginalChecksum=b2b8b83e932fca6d46072083f20a0c76 (do not edit this line) */
